import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.Basic
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.SourcePackage
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.SourceDependencies
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.Formalization
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.ReviewerBridge
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.TheoremStatement
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.MathlibObjects
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.AdmissibleClass
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.Projection
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.BridgeLemmas
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.GateLemmas
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.FinalTheorem
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.ExponentialFamily
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.Sufficiency
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.NeymanPearson
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.MLEConsistency
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.SequentialAnalysis
import FuzzinessSequentialStatisticalMethodsCanonicalLaneLean.FuzzyData

namespace HautevilleHouse
namespace FuzzinessSequentialStatisticalMethodsCanonicalLaneLean

-- The root module aggregates all domain packages.

theorem domain_ready : True := by
  trivial

end FuzzinessSequentialStatisticalMethodsCanonicalLaneLean
end HautevilleHouse